### ISSUE TITLE
HTTPS/SSL?

### ISSUE THREAD

**Issue by ericoc** [zeromonio/zeromon#1]
Unfortunately, deploying this playbook or using the AWS AMI currently only provides you with a default Zabbix installation running on Apache with no HTTPS/SSL support. Apache ends up configured to only listen on port 80 with a single `_default_:80` virtual host for Zabbix.

It would be amazing to have a second Apache virtual host configured for `_default_:443`. Preferably, the HTTP virtual host could even do a `301 Permanent Redirect` to the HTTPS/SSL virtual host, significantly improving the web security of the Zabbix installation.

This could probably be done _relatively_ easily via an ACME client or LetsEncrypt if I did a little more research on how that works? Unfortunately, I think the big downside is that AWS EC2 host names are generally very random and unknown. In my experience, EC2 host names are similar to `ip-172-etc123` making them unpredictable? I would suspect that the host name internal to the EC2 instance would need to be set _before_ an SSL certificate is generated and configured.

I definitely need to do more research and think harder about this problem. Configuring Apache to use an SSL certificate is the easy part, but generating and renewing the SSL certificate is complicated from my perspective, due to the host name randomness.

**Comment by ericoc** [comment]
This also is not a show-stopper or blocker for users by any means, if you currently _have_ your own SSL certificate and wanted to use it. You could definitely set up an AWS Elastic Load Balancer (ELB) and have the SSL certificate terminate HTTPS on the ELB. You could then have the Zeromon Zabbix installation running regularly on HTTP on EC2, but use HTTPS via the ELB in front of the EC2 instance.

**Comment by kyleparisi** [comment]
The instance owner would need the instance to be live before they could update a dns record for a cert.  There might not be a fool proof solution and may have to stick with instance owner having to implement.  I think at best we could provide a programmatic, random, subdomain to zeromon.io?  Then apply the cert to that?

**Comment by ericoc** [comment]
I don't really love the idea of a EC2 instance owner depending on a DNS name that we control, much less a randomized one. I sort of feel like the whole purpose of an AMI is that it allows someone to create their own complete Zabbix installation without permanently relying on third-party stuff. The AMI already depends on the Zabbix .deb repository and this GitHub repository. I would prefer to minimize dependencies as much as possible. A permanent DNS name would be a huge dependency completely out of the EC2 owners control, wouldn't it?

**Comment by kyleparisi** [comment]
Indeed. Might be dead in the water.

**Comment by ericoc** [comment]
This might be realistic with the DigitalOcean Marketplace! Valid working host names that actually resolve combined with Let's Encrypt or Certbot or whatever seem a lot more realistic on DigitalOcean.

**Comment by ericoc** [comment]
Implemented certbot per https://github.com/zeromonio/zeromon/commit/a0e8c21c523d6af5635434d8eb4f90285e74d6d8 💥 see https://github.com/zeromonio/zeromon#httpsssl-optional for instructions!
